-- Builds online/driftfactory.lua: CSP loads an online script from a single
-- URL, so the app's modules are inlined ahead of online/main.lua.
-- Run from the repository root:  lua online/build.lua
local repo = (arg and arg[0] or ''):match('^(.*)[/\\]online[/\\]build%.lua$') or '.'
local srcDir = repo .. '/ac-lua/DriftFactoryJudgeApp/src/'

-- Every module the online script uses, in no particular order (each is
-- loaded lazily on first require).
local modules = {
  'util', 'defaults', 'geometry', 'profiles', 'model', 'results', 'scoring',
  'calibration', 'leaderboard', 'official_layout', 'session', 'editor',
  'draw', 'ui_app', 'context', 'storage_online',
}

local function read(path)
  local file = assert(io.open(path, 'rb'), 'missing ' .. path)
  local content = file:read('a')
  file:close()
  return (content:gsub('\r\n', '\n'))
end

local out = {}
local function emit(text) out[#out + 1] = text end

emit([[
-- Drift Factory Judge App — online script (GENERATED by online/build.lua,
-- do not edit by hand; edit online/main.lua or ac-lua/DriftFactoryJudgeApp/src).
--
-- A modified version of DriftJudging SP by DeadEndReece
-- (Copyright (C) 2026 DeadEndReece), used and modified under the GNU Affero
-- General Public License v3.0 plus the additional attribution terms in
-- LICENSE.md. Not an official DriftJudging SP release; DriftFactory is not
-- affiliated with or endorsed by DeadEndReece.
-- Source, credits and license: https://github.com/insidedacoolest/drift-jury

local __bundled, __loaded = {}, {}
local __require = require
local function require(name)
  if __loaded[name] ~= nil then return __loaded[name] end
  local loader = __bundled[name]
  if not loader then return __require(name) end
  local value = loader()
  __loaded[name] = value == nil and true or value
  return __loaded[name]
end
]])

for _, name in ipairs(modules) do
  local code = read(srcDir .. name .. '.lua')
  emit(string.format('\n__bundled[%q] = function()\n%s\nend\n', 'src.' .. name, code))
end

emit('\n-- online/main.lua\n')
emit(read(repo .. '/online/main.lua'))

local target = repo .. '/online/driftfactory.lua'
local file = assert(io.open(target, 'wb'))
file:write(table.concat(out))
file:close()
print('wrote ' .. target)
